name: "Golang Test Report"
description: "Parse Golang json test report and generate a human readable summary"
inputs:
  input:
    description: "Test report json file path"
    required: true
  output:
    description: "Output file path. Default is $GITHUB_STEP_SUMMARY which is the default output for GitHub Actions"
    default: "$GITHUB_STEP_SUMMARY"
    required: false
  template:
    description: "Template file. Default will be used if empty"
    required: false
  templateVariables:
    description: "Variables for template files. Default will be used if empty"
    required: false
runs:
  using: "composite"
  steps:
    - name: "Check Go version"
      id: go-version-check
      shell: bash
      run: |
        semver () {
            if [[ $1 == $2 ]]
            then
                return 0
            fi
            local IFS=.
            local i ver1=($1) ver2=($2)
            # fill empty fields in ver1 with zeros
            for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
            do
                ver1[i]=0
            done
            for ((i=0; i<${#ver1[@]}; i++))
            do
                if ((10#${ver1[i]:=0} > 10#${ver2[i]:=0}))
                then
                    return 1
                fi
                if ((10#${ver1[i]} < 10#${ver2[i]}))
                then
                    return 2
                fi
            done
            return 0
        }

        if go version &>/dev/null; then
            INSTALLED_GO_VERSION=$(go version | awk '{print $3}' | sed 's/go//')
            semver $INSTALLED_GO_VERSION 1.18
            if [ $? -lt 2 ]; then
                echo "setup-go-required=false"
            else
                echo "setup-go-required=true"
            fi
        else
            echo "setup-go-required=true"
        fi
    - name: "Set up Go"
      if: env.setup-go-required == 'true'
      uses: actions/setup-go@v5
      with:
        go-version: 1.23
    - name: "Install go-testreport"
      shell: bash
      run: |
        cd $GITHUB_ACTION_PATH
        go install ./
    - name: "Create Report"
      shell: bash
      run: go-testreport -vars="${{ inputs.templateVariables }}" -template="${{ inputs.template }}" -input="${{ inputs.input }}" -output="${{ inputs.output }}"
branding:
  icon: "check-circle"
  color: "blue"
