name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Build
        run: go build -v ./cmd/TestReport
      - name: Test
        run: |
          ls
          go test -v ./... -json | TestReport >> $GITHUB_STEP_SUMMARY
