name: Go

on:
  push:
    branches: ["main"]
    tags: "*"
  pull_request:
    branches: ["main"]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Markup Link Checker (mlc)
        uses: becheran/mlc@v0.21.0
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.63
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Install go-testreport
        run: go install github.com/becheran/go-testreport@main
      - name: Test
        run: go test ./... -json | go-testreport -vars="Title:Test Report Linux" > $GITHUB_STEP_SUMMARY
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Install go-testreport
        run: go install github.com/becheran/go-testreport@main
      - name: Test
        run: go test ./... -json | go-testreport -vars="Title:Test Report Windows" > $env:GITHUB_STEP_SUMMARY
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
